### ISSUE TITLE
Clarification of dependencies

### ISSUE THREAD

**Issue by verdurin** [cancerit/alleleCount#18]
This is related to #17 but anyway, in README.md, it refers to a file `INSTALL`, that lists all the external dependencies. That file is not included in the distribution.

It also looks like Bio-SamTools is required, not just samtools itself. Is that the correct interpretation?

**Comment by verdurin** [comment]
The reason I'm asking is that I'm building an EasyBuild easyconfig for alleleCount.

**Comment by keiranmraine** [comment]
I'd not recommend building the perl side of things, it's soon to be completely removed as the C implementation allows CRAM use in addition to BAM. @drjsanger do you have time to review the later versions of htslib to see if the patch step can be dropped?  If so we can simplify this down to a simple make based project during the re-release.

**Comment by verdurin** [comment]
That's a useful clarification, thanks.

It would also be very helpful to know whether I can specify upstream versions of htslib as a dependency, as you say.

**Comment by verdurin** [comment]
@keiranmraine - Any news on the removal of the patch and the Perl parts?

**Comment by keiranmraine** [comment]
@drjsanger can you comment on this when you are back in the office?

**Comment by drjsanger** [comment]
@keiranmraine I've checked the htslib code and have run a quick test with 1.3. 

If we were to install htslib version 1.3 or above the change is already in the code. Versions below would require the patch (version dependent).

**Comment by keiranmraine** [comment]
So we've decided to keep the perl version, but it now used Bio::DB::HTS, so both this and the C version are equivalent again.  Next release will encompass all of these changes.
