### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by keyuan** [cancerit/alleleCount#34]
Dear Keiran and David 
I'm having the following problem when running the setup script. Could you please help me?
Many thanks, ke

-n Building alleleCounter ...
rm -f ./src/*.o *~ ./bin/alleleCounter ./bin/* ./tests/tests_log ./tests/bam_access_tests ./src/*.gcda ./src/*.gcov ./src/*.gcno *.gcda *.gcov *.gcno ./tests/*.gcda ./tests/*.gcov ./tests/*.gcno
rm: ./bin/alleleCounter.dSYM: is a directory
make: *** [clean] Error 1

**Comment by keiranmraine** [comment]
Hi @keyuan , please could you provide the following information:

1. Operating system
2. Attach the full output of `setup.sh` by redirecting stdout+stderr to file

Thanks

**Comment by keiranmraine** [comment]
Please reopen if you are still having difficulties.
