### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by mheskett** [cancerit/alleleCount#36]
`! Configure failed for Bio-DB-HTS-2.9. See /home/users/heskett/.cpanm/work/1515532118.89002/build.log for details.
! Installing the dependencies failed: Module 'Bio::DB::HTS' is not installed
! Bailing out the installation for alleleCount-v3.3.1.`

linux 3.10.0-514.16.1.el7.x86_64

the build log says the same--> biodbhts is not installed. But isn't this included?

thanks!

**Comment by keiranmraine** [comment]
Hi @mheskett , please could you provide the following information:

1. Operating system (I think RedHat from the above string)
2. Attach the full output of `setup.sh` by redirecting stdout+stderr to file

This looks like htslib has failed to build rather than the perl-lib.

Thanks

**Comment by keiranmraine** [comment]
Just read your previous issue that you closed where autodie was not found.  This would suggest you were attempting to install with perl <5.10.1 (~2007 release, 7 years prior to this repository being created) as it has been a core library since then.

If you've resumed an install after changing to point to a newer perl you will need to start the build process from a clean checkout/archive, or delete the `install_tmp` folder before running `./setup.sh <install_loc>`

**Comment by mheskett** [comment]
[build.log](https://github.com/cancerit/alleleCount/files/1620557/build.log)

CentOS Linux release 7.3.1611 (Core)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.3.1611 (Core)
CentOS Linux release 7.3.1611 (Core)

**Comment by keiranmraine** [comment]
Please can you provide the command you used to invoke this build?  The log you have provided suggests that you have run the perl Makefile rather than `setup.sh <INSTALL TO>` as there should be install steps for the C libraries performed separately to the perl modules.

**Comment by keiranmraine** [comment]
I've just run a build on a clean image of CentOS 7:

```
$ hostnamectl
   Static hostname: centos.localdomain
Transient hostname: centos
         Icon name: computer-vm
           Chassis: vm
        Machine ID: 56d65f493d8f854534fe792ecf014b83
           Boot ID: 3b491dbb00164441b630e9aab9971206
    Virtualization: kvm
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-327.28.3.el7.x86_64
      Architecture: x86-64
```

I had to add some packages but it does build fine.  Below is my history, I've deleted commands where I was trying to find relevant packages.

Unfortunately RedHat/CentOS are known for removing thing from the core perl release which confuses matter.

```
    5  sudo yum install bzip2
    6  sudo yum install autoconf automake gcc libtool make pkgconfig zlib-devel libcurl-devel
    7  sudo yum install autoconf zlib-devel libcurl-devel openssl-devel ncurses-devel 
    8  sudo yum install perl perl-devel perl-Test-Simple perl-libwww-perl perl-autodie
    9  curl -sSL https://github.com/cancerit/alleleCount/archive/v3.3.1.tar.gz | tar zx
   10  cd alleleCount-3.3.1/
   11  ./setup.sh ~/local
   12  history
```

Can you try this please?

**Comment by mheskett** [comment]
Thanks for the help! Tried again and I think there is success, here is the only error:

`[fai_load] build FASTA index.
[fai_load] build FASTA index.
./src/alleleCounter.c: In function ‘main’:
./src/alleleCounter.c:386:7: warning: unused variable ‘line’ [-Wunused-variable]
  char line[512];
       ^
tests/bam_access_tests.c: In function ‘test_bam_access_get_position_base_counts’:
tests/bam_access_tests.c:43:6: warning: variable ‘res’ set but not used [-Wunused-but-set-variable]
  int res = bam_access_get_position_base_counts(chr,pos,stats);`

I noticed that your readme doesn't document usage. How do I use aC?

**Comment by keiranmraine** [comment]
That's just a warning that a return value is not checked, quite common.

Provided you've installed to a location on your path (or added to your path)

```
alleleCounter --help
```

If not on path:

```
<install_loc>/bin/alleleCounter --help
```

I'll get that added to the current feature were working on (which removes most of the perl dependencies to simplify install).

**Comment by keiranmraine** [comment]
More detail is available now on the current work branch:

https://github.com/cancerit/alleleCount/blob/feature/overlapping_reads/README.md#usage
