### ISSUE TITLE
allelecount runs endlessly or gets killed on CentOS 7

### ISSUE THREAD

**Issue by mheskett** [cancerit/alleleCount#41]
allelecount runs endlessly without printing anything to results file or gets killed when using a large loci file. Even when allocating huge amounts of resources (16cpu, 90GB RAM). On centOS 7--works when I downsample the loci file down to a toy number of lines so I know none of the files are misformatted. Is there a max size for the loci file?

**Comment by keiranmraine** [comment]
alleleCount doesn't use multiple CPUs:

1. Have you verified that the BAM and it's index are intact.
    * Long running and huge memory resources often point to these being corrupted (especially the index).
    * Check the BAM with `samtools view your.bam > /dev/null ; echo "EXIT CODE: $?"`
    * Copy the old index away, regenerate and compare to the original.
1. How big is the loci file?
1. Has the file been sorted appropriately? (`sort -k1,1 -k2,2n`)
1. Have you used the `--dense-snps` option?
1. Is output being generated?

**Comment by mheskett** [comment]
okay I think sorting the loci file solved it. 

however it does seem slow. 1000G has 80M snps--it appears this would take days of compute per bam. suggestions?

**Comment by keiranmraine** [comment]
The 1000g data set has a high frequency of SNPs with very small intervals, this results in the same blocks of the BAM file being re-read and decompressed multiple times.  Please use the `--dense-snps` option as indicted above.  This switches to a streaming approach which is far faster in these circumstances.
