### ISSUE TITLE
test failed: t/01bam.t .... Failed 235/235 subtests 

### ISSUE THREAD

**Issue by weiliuyuan** [cancerit/alleleCount#42]
_Hi, 
I am trying to install alleleCount-3.3.1 on Ubuntu 16.04 but couldn't pass the test: 
" t/01bam.t .... Failed 235/235 subtests" 
I have the same issue when installing PCAP-core-4.0.5. 
Would really appreciate if you can give me some advice here. 
I have attached my screen output here:_

Max compilation CPUs set to 6
App::cpanminus is up to date. (1.7043)
Previously installed base perl deps...
 already staged ...
Building Bio::DB::HTS ...
ls
echo '/* Empty config.h generated by Makefile */' > config.h
echo '#define HTS_VERSION "1.3.2"' > version.h
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o kfunc.o kfunc.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o knetfile.o knetfile.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o kstring.o kstring.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o bgzf.o bgzf.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o faidx.o faidx.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o hfile.o hfile.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o hfile_net.o hfile_net.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o hts.o hts.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o md5.o md5.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o regidx.o regidx.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o sam.o sam.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o synced_bcf_reader.o synced_bcf_reader.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o vcf_sweep.o vcf_sweep.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o tbx.o tbx.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o vcf.o vcf.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o vcfutils.o vcfutils.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/cram_codecs.o cram/cram_codecs.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/cram_decode.o cram/cram_decode.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/cram_encode.o cram/cram_encode.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/cram_external.o cram/cram_external.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/cram_index.o cram/cram_index.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/cram_io.o cram/cram_io.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/cram_samtools.o cram/cram_samtools.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/cram_stats.o cram/cram_stats.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/files.o cram/files.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/mFILE.o cram/mFILE.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/open_trace_file.o cram/open_trace_file.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/pooled_alloc.o cram/pooled_alloc.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/rANS_static.o cram/rANS_static.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/sam_header.o cram/sam_header.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/string_alloc.o cram/string_alloc.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/thread_pool.o cram/thread_pool.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/vlen.o cram/vlen.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o cram/zfio.o cram/zfio.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o kfunc.pico kfunc.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o knetfile.pico knetfile.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o kstring.pico kstring.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o bgzf.pico bgzf.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o faidx.pico faidx.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o hfile.pico hfile.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o hfile_net.pico hfile_net.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o hts.pico hts.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o md5.pico md5.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o regidx.pico regidx.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o sam.pico sam.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o synced_bcf_reader.pico synced_bcf_reader.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o vcf_sweep.pico vcf_sweep.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o tbx.pico tbx.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o vcf.pico vcf.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o vcfutils.pico vcfutils.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/cram_codecs.pico cram/cram_codecs.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/cram_decode.pico cram/cram_decode.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/cram_encode.pico cram/cram_encode.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/cram_external.pico cram/cram_external.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/cram_index.pico cram/cram_index.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/cram_io.pico cram/cram_io.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/cram_samtools.pico cram/cram_samtools.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/cram_stats.pico cram/cram_stats.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/files.pico cram/files.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/mFILE.pico cram/mFILE.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/open_trace_file.pico cram/open_trace_file.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/pooled_alloc.pico cram/pooled_alloc.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/rANS_static.pico cram/rANS_static.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/sam_header.pico cram/sam_header.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/string_alloc.pico cram/string_alloc.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/thread_pool.pico cram/thread_pool.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/vlen.pico cram/vlen.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -fpic -c -o cram/zfio.pico cram/zfio.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o bgzip.o bgzip.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o htsfile.o htsfile.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o tabix.o tabix.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o test/fieldarith.o test/fieldarith.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o test/hfile.o test/hfile.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o test/sam.o test/sam.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o test/test-regidx.o test/test-regidx.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o test/test_view.o test/test_view.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o test/test-vcf-api.o test/test-vcf-api.c
gcc -g -Wall -O2 -fPIC -Wno-unused -Wno-unused-result -I.  -c -o test/test-vcf-sweep.o test/test-vcf-sweep.c
ar -rc libhts.a kfunc.o knetfile.o kstring.o bgzf.o faidx.o hfile.o hfile_net.o hts.o md5.o regidx.o sam.o synced_bcf_reader.o vcf_sweep.o tbx.o vcf.o vcfutils.o cram/cram_codecs.o cram/cram_decode.o cram/cram_encode.o cram/cram_external.o cram/cram_index.o cram/cram_io.o cram/cram_samtools.o cram/cram_stats.o cram/files.o cram/mFILE.o cram/open_trace_file.o cram/pooled_alloc.o cram/rANS_static.o cram/sam_header.o cram/string_alloc.o cram/thread_pool.o cram/vlen.o cram/zfio.o
ranlib libhts.a
gcc -pthread  -o bgzip bgzip.o libhts.a -lz 
gcc -pthread  -o htsfile htsfile.o libhts.a -lz 
gcc -pthread  -o tabix tabix.o libhts.a -lz 
gcc -pthread  -o test/fieldarith test/fieldarith.o libhts.a -lz 
gcc -pthread  -o test/hfile test/hfile.o libhts.a -lz 
gcc -pthread  -o test/sam test/sam.o libhts.a -lz 
gcc -pthread  -o test/test-regidx test/test-regidx.o libhts.a -lz 
gcc -pthread  -o test/test_view test/test_view.o libhts.a -lz 
gcc -pthread  -o test/test-vcf-api test/test-vcf-api.o libhts.a -lz 
gcc -pthread  -o test/test-vcf-sweep test/test-vcf-sweep.o libhts.a -lz 
gcc -shared -Wl,-soname,libhts.so.1 -pthread  -o libhts.so kfunc.pico knetfile.pico kstring.pico bgzf.pico faidx.pico hfile.pico hfile_net.pico hts.pico md5.pico regidx.pico sam.pico synced_bcf_reader.pico vcf_sweep.pico tbx.pico vcf.pico vcfutils.pico cram/cram_codecs.pico cram/cram_decode.pico cram/cram_encode.pico cram/cram_external.pico cram/cram_index.pico cram/cram_io.pico cram/cram_samtools.pico cram/cram_stats.pico cram/files.pico cram/mFILE.pico cram/open_trace_file.pico cram/pooled_alloc.pico cram/rANS_static.pico cram/sam_header.pico cram/string_alloc.pico cram/thread_pool.pico cram/vlen.pico cram/zfio.pico -lz -lm 
ln -sf libhts.so libhts.so.1
Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'Bio-DB-HTS' version '2.3'
x86_64-linux-gnu-gcc -I/home/keyuan/battenberg_related/alleleCount-3.3.1/install_tmp/bioDbHts/htslib/htslib -I/usr/lib/x86_64-linux-gnu/perl/5.22/CORE -DVERSION="2.3" -DXS_VERSION="2.3" -fPIC -D_IOLIB=2 -D_FILE_OFFSET_BITS=64 -Wno-error -Wformat=0 -Wno-unused-result -c -D_REENTRANT -D_GNU_SOURCE -DDEBIAN -fwrapv -fno-strict-aliasing -pipe -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -g -o lib/Bio/DB/HTS.o lib/Bio/DB/HTS.c
ExtUtils::Mkbootstrap::Mkbootstrap('blib/arch/auto/Bio/DB/HTS/HTS.bs')
x86_64-linux-gnu-gcc -shared -L/usr/local/lib -fstack-protector-strong -o blib/arch/auto/Bio/DB/HTS/HTS.so lib/Bio/DB/HTS.o -L/home/keyuan/battenberg_related/alleleCount-3.3.1/install_tmp/bioDbHts/htslib -Wl,-rpath,/home/keyuan/battenberg_related/alleleCount-3.3.1/install_tmp/bioDbHts/htslib -lhts -lpthread -lz
x86_64-linux-gnu-gcc -I/home/keyuan/battenberg_related/alleleCount-3.3.1/install_tmp/bioDbHts/htslib/htslib -I/usr/lib/x86_64-linux-gnu/perl/5.22/CORE -DVERSION="2.3" -DXS_VERSION="2.3" -fPIC -D_IOLIB=2 -D_FILE_OFFSET_BITS=64 -Wno-error -Wformat=0 -Wno-unused-result -c -D_REENTRANT -D_GNU_SOURCE -DDEBIAN -fwrapv -fno-strict-aliasing -pipe -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -g -o lib/Bio/DB/HTS/Faidx.o lib/Bio/DB/HTS/Faidx.c
ExtUtils::Mkbootstrap::Mkbootstrap('blib/arch/auto/Bio/DB/HTS/Faidx/Faidx.bs')
x86_64-linux-gnu-gcc -shared -L/usr/local/lib -fstack-protector-strong -o blib/arch/auto/Bio/DB/HTS/Faidx/Faidx.so lib/Bio/DB/HTS/Faidx.o -L/home/keyuan/battenberg_related/alleleCount-3.3.1/install_tmp/bioDbHts/htslib -Wl,-rpath,/home/keyuan/battenberg_related/alleleCount-3.3.1/install_tmp/bioDbHts/htslib -lhts -lpthread -lz
t/00_load.t .. ok   
t/01bam.t .... Failed 235/235 subtests 
t/02faidx.t .. ok     
t/04tabix.t .. ok     
t/05vcf.t .... ok       
t/06kseq.t ... ok     

Test Summary Report
t/01bam.t  (Wstat: 139 Tests: 0 Failed: 0)
  Non-zero wait status: 139
  Parse errors: Bad plan.  You planned 235 tests but ran 0.
Files=6, Tests=245,  0 wallclock secs ( 0.03 usr  0.01 sys +  0.53 cusr  0.04 csys =  0.61 CPU)
Result: FAIL
Failed 1/6 test programs. 0/245 subtests failed.

_Many thanks! 
Vivi_

**Comment by keiranmraine** [comment]
That failure is in the building of `Bio::DB::HTS`.  Our [travis build](https://travis-ci.org/cancerit/alleleCount/jobs/256897542) for the release you indicate shows this compiling correctly on [Ubuntu Trusty](https://travis-ci.org/cancerit/alleleCount/jobs/256897542/config).

I've just run a build on a clean Ubuntu 16.04.1 and provided all of the apt packages listed in [`.travis`](https://github.com/cancerit/alleleCount/blob/e16b76df5f159d53c74d720af6247067afa6270f/.travis.yml) plus the additional `libssl-dev` [1] are installed it works fine.

Check the perl version you are using, 16.04 should have 5.22.1 unless you've changed it.

If you continue to have problems you could try building [`Bio::DB::HTS`](https://github.com/Ensembl/Bio-DB-HTS) using their installer to see if that works directly [2].

1. seems specific to Xenial build, or already on travis base image
2. Our tools build it slightly differently as that installer always pulls the latest version of `Bio::DB::HTS` regardless of what you checkout.

**Comment by weiliuyuan** [comment]
Hi Keiran, 

Thank you so much for the help. i have installed Bio::DB::HTS and update my perl to 5.22.1 and alleleCount works now. But i still have the same error when i install PCAP-core... 

Best,
Vivi

**Comment by keiranmraine** [comment]
I can see the problem in PCAP-core, it expects to build Bio::DB::HTS regardless of an existing install (alleleCount checks for a compatible one).

What I'd recommend is building Bio::DB::HTS again with the '--static' option and then rerun the PCAP-core `setup.sh` script.  When it fails run `touch install_tmp/biohts.success` and rerun `setup.sh`.

We're currently working on a new release for PCAP and we will revisit Bio::DB::HTS install to resolve this issue.
