### ISSUE TITLE
int(block_str) error

### ISSUE THREAD

**Issue by girdhar3** [cancerit/alleleCount#44]
I am running allelecount on my bam files and WGS vcf file
for some files
I am getting this error

ValueError: invalid literal for int() with base 10: ''
    block = int(block_str) - 1;

in which case, this would happen

 "python /hpc/users/girdhk01/psychencode/files/bin/allelecounter/allelecounter.py --vcf $VCF \
                         --sample $WGS_NAME${chr_no}\
                         --bam $BAM_file \
                         --ref $REF \
                         --min_cov 2 \
                         --min_baseq 2 \
                         --min_mapq 2 \
                         --max_depth 100000 \
                         --o ${BAM_SAMPLE_NAME}_${chr_no}.ac.vcf"
done

**Comment by keiranmraine** [comment]
Can you try reproducing this with the codebase held here?  This is the site for the underlying C codebase.

Check which version of the C code it is with:

```
alleleCounter --version
```

And try your data using it directly, see `alleleCounter --help`.

**Comment by drjsanger** [comment]
The error you're getting is a Python error. Our package `alleleCounter` is available as C binaries or with a perl wrapper. Perhaps this is an issue for the developers of `/hpc/users/girdhk01/psychencode/files/bin/allelecounter/allelecounter.py`? Is this code wrapping our tools? Please reopen if required.
