### ISSUE TITLE
Indel support

### ISSUE THREAD

**Issue by ibwoo** [cancerit/alleleCount#50]
Is it possible that this tool will ever offer support for counting indels?

**Comment by AndyMenzies** [comment]
No, thats not what this tool is for.  AlleleCount will tell you how many times A, C, G and T are seen at specified single point locations within a bam file.  Accurate counting of indels usually involves remapping reads, and that is outside of the scope of this application.

If you are interested in indel detection we have [cgpPindel](https://github.com/cancerit/cgpPindel)
