### ISSUE TITLE
Running alleleCounter with or without reference file

### ISSUE THREAD

**Issue by ilykos** [cancerit/alleleCount#52]
Hi, 

I may have missed this, but providing "reference file" (-r flag) is marked as optional in the help section.

Are there any advantages/disadvantages of providing reference file to alleleCounter?

Thanks.

**Comment by drjsanger** [comment]
The reference file option was mainly provided for use when giving CRAM as input in case the reference was not embedded in the CRAM file. Using BAM you should see no difference.
