### ISSUE TITLE
AlleleCounter for unpaired data

### ISSUE THREAD

**Issue by m4merg** [cancerit/alleleCount#53]
When I try to run alleleCounter for unpaired seq data i get 0's for all positions, though samtools depth gives me proper results (high coverage of selected positions). Sam header for the dataset im trying to analyse is in concordance with loci file. 
I found that Genotype.pm module requires sam flag 2 (read paired). Though, if I change it to 0, soft still dont give me proper result.
So is alleleCounter intended for the use for unpaired data? Or there is another kind of problem with dataset im using?

**Comment by AndyMenzies** [comment]
All of our data is paired end data, we've never tried running it over single-end data.

Going from the documentation on samtools flags, I think you will also need to remove the '8' flag from the filter as well. To give a final filter value of 3844

If you use the c implementation of alleleCounter (which perl wraps, and you will have installed as part of the same project) you don't need to edit the code as both filter include (-f) and filter exclude (-F) parameters can be specified.  ie

`alleleCounter -f 0 -F 3844 -l locus.txt -b sample.cram -o counts.out`
