### ISSUE TITLE
Running aC on scRNA BAMs (10X or otherwise)

### ISSUE THREAD

**Issue by nansari-pour** [cancerit/alleleCount#61]
Hi there,
Is is essential for the HTS file to be paired-end for aC to work?
Specifically, aC only gives 0 counts (and 0 depth) when supplied with an scRNA BAM file.
Is there any way around this?
Thanks

**Comment by keiranmraine** [comment]
Not too clear what you are after here.  By aC do you mean `alleleCounter`?

Allele counter acts on a single BAM/CRAM file.  All values being 0 is more likely to be due to the input loci BED file (`--loci-file`) being for the incorrect genome build (chr vs no chr prefix).

**Comment by drjsanger** [comment]
I would add that it may be due to default flag filtering. See `-f  --required-flag` and `-F  --filtered-flag` options and select an appropriate value for your data. I find [this site](http://broadinstitute.github.io/picard/explain-flags.html) useful for working out flag values.

**Comment by nansari-pour** [comment]
Dear Keiran and David,


1) I am aware of the requirement for matching genome build but the problem is definitely not the chromosome prefix/annotation.

2) the flag option worked beautifully! Many thanks for your advice and the provided link.

Best,

Naser
________________________________

**Comment by drjsanger** [comment]
@nansari-pour Glad we could get it working for you.
