### ISSUE TITLE
Can I use this tools on RNAseq BAM file ?

### ISSUE THREAD

**Issue by SeqCrafter** [cancerit/alleleCount#73]
I want to calculate the allele-based expression using ASCAT-V3.0 gave loci's file, Dose this tool suit for that?

**Comment by AndyMenzies** [comment]
We have no experience with ASCAT3.0, we're more familiar with 2.5.X. Assuming the loci file format hasn't changed in the new release, alleleCount should work.

**Comment by SeqCrafter** [comment]
> We have no experience with ASCAT3.0, we're more familiar with 2.5.X. Assuming the loci file format hasn't changed in the new release, alleleCount should work.

Thank you for your quickly reply. I got it
