### ISSUE TITLE
Scipt convertAlleleCounts.r deleted?

### ISSUE THREAD

**Issue by justalilibit** [cancerit/alleleCount#75]
Hi!

I have noticed that the script for convertAlleleCounts.r is not found anymore. However, the step is still listed on the [nextflow website](https://nf-co.re/sarek/2.7.1/output#convertallelecounts) under "outputs docs".
Is there a reason it was deleted? Is it still available somewhere?

**Comment by davidrajones** [comment]
Hi, @justalilibit .

`convertAlleleCounts.r` was never part of alleleCount itself. As a group we haven't written the nf-core pipeline or contributed to it I'm afraid. A quick delve into the nf-core docs shows me it seems to have existed as part of the [Sarek pipeline](https://nf-co.re/sarek/2.7.1/output#convertallelecounts). The link to the script fron that documentation leads us to [the script page](https://github.com/nf-core/sarek/blob/master/bin/convertAlleleCounts.r) which doesn't exist anymore. I would suggest contacting the maintainers of the Sarek pipeline. I hope you find a solution. 

Regards,

David
