### ISSUE TITLE
Is LWP::UserAgent required?

### ISSUE THREAD

**Issue by ItIsI-Orient** [cancerit/alleleCount#77]
Hi, I am trying to build this package from source with local-only dependencies and I would like to know, whether the Perl package LWP::UserAgent is required for this package to function properly. I see that you are installing it in the `opt-build` script, but it is not mentioned in the `perl/Makefile.PL` as a prerequisite.

**Comment by AndyMenzies** [comment]
Hi

I suspect the line in the opt-build script was copied from a similar project, we were converting a number of repo's to use docker at about the same time and its possible this extra bit just crept in.  I don't think this project has ever used LWP::UserAgent directly, its possible a dependancy does but that would install it itself.

Andy
